POST http://localhost:3333/transactions
Content-Type: application/json

{
  "description": "Groceries",
  "price": 312,
  "category": "Food",
  "type": "outcome",
  "createdAt": "2023-09-20T19:09:17.527Z"
}

###

GET http://localhost:3333/transactions
Content-Type: application/json,
Access-Control-Allow-Origin: http://localhost:5173,

###


DELETE http://localhost:3333/transactions/ecdcf4d9-a805-413a-bf92-6e9e14025422
